# Generated by Django 3.0.8 on 2020-07-30 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Імя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('date_of_birth', models.DateTimeField(auto_now_add=True, verbose_name='Дата народження')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Order', verbose_name='Замовлення')),
            ],
        ),
    ]
