# Generated by Django 3.0.8 on 2020-07-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='register_date',
            field=models.DateField(verbose_name='Дата реєстрації'),
        ),
    ]
